### ISSUE TITLE
Incorrect content for ncp-uart-nsw_6.7.9_115200.ota

### ISSUE THREAD

**Issue by damdo** [vahempio/Tasmota-for-eWeLink#1]
### PROBLEM DESCRIPTION
The bin file under `bin/ncp-uart-nsw_6.7.9_115200.ota` is not a real ota file but seems to be an HTML.

### REQUESTED INFORMATION
--

### TO REPRODUCE
Check file content

### EXPECTED BEHAVIOUR
File to look similar to https://github.com/arendst/Tasmota/blob/development/tools/fw_SonoffZigbeeBridge_ezsp/ncp-uart-nsw_6.7.9_115200.ota

### SCREENSHOTS
--
### ADDITIONAL CONTEXT
--

**Comment by vahempio** [comment]
Thank you very much @damdo for the catch, and this is now fixed with [6b6b916271f6897639f233b314a61b5d158ca684](https://github.com/vahempio/Tasmota-for-eWeLink/commit/6b6b916271f6897639f233b314a61b5d158ca684).

Happy hacks!
