### ISSUE TITLE
ZB-GW03-V1.4 compatibility

### ISSUE THREAD

**Issue by nistvan86** [vahempio/Tasmota-for-eWeLink#10]
I've received my gateway today and it has the V1.4 revision of the PCB.
Should this work with this firmware the same way?

![20231205_012526](https://github.com/vahempio/Tasmota-for-eWeLink/assets/829428/28d9ff00-0673-4daf-8f37-70dd3baade02)

**Comment by tyjtyj** [comment]
do u managed to get it work ? i flashed the zigbee firmware and it stuck in boot loop

**Comment by nistvan86** [comment]
I did, it's being used ever since. But it was long ago, I don't find my notes of what firmware version I've used.
I remember I needed multiple steps, maybe this one was it https://github.com/arendst/Tasmota/discussions/12764#discussioncomment-6340566 

(but I'm closing the Github issue, as it's resolved on my side)

**Comment by vahempio** [comment]
Sorry, I missed the initial issue creation notification. Yes the v1.4 is fully compatible, as you have experienced.
@tyjtyj, you can use the firmware located inside the 'bin' directory with the ncsp prefix: it is not the most up to date, but at least this is the version that I currently use wirhout any issue.

**Comment by tyjtyj** [comment]
Guys thx for reply. There are so many guide there and I unfortunately pick version 11 which don't work on on 1.4. After each flash of esp firmware, I lost connection to whole device. After few googling and found the one works. Just remember to full reset if eth not working.
Thanks everyone who replied.
https://github.com/arendst/Tasmota/discussions/12764
