### ISSUE TITLE
ETH not working

### ISSUE THREAD

**Issue by dongourdet** [vahempio/Tasmota-for-eWeLink#5]
### PROBLEM DESCRIPTION
backlog Template {"NAME":"ZB-GW03-V1.3","GPIO":[0,0,3552,0,3584,0,0,0,5793,5792,320,544,5536,0,5600,0,0,0,0,5568,0,0,0,0,0,0,0,0,608,640,32,0,0,0,0,0],"FLAG":0,"BASE":1} ; module 0

but i cannot get ETHERNET to work.
Nothing shows in the Console about ETH.
In my router i do not get a DHCP record.
Can you help me out?

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [x] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:
Used


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_
backlog Template {"NAME":"ZB-GW03-V1.3","GPIO":[0,0,3552,0,3584,0,0,0,5793,5792,320,544,5536,0,5600,0,0,0,0,5568,0,0,0,0,0,0,0,0,608,640,32,0,0,0,0,0],"FLAG":0,"BASE":1} ; module 0

but i cannot get ETHERNET to work.
Nothing shows in the Console about ETH.
In my router i do not get a DHCP record.
Can you help me out?

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by vahempio** [comment]
Hi,
I suggest you to perform a flash erase and then write again the full firmware. Sometimes, I observe bad behavior when the firmware is applied up to an existing firmware : start from a blank flash and flash the ethernet firmware directly.

Also, you can try the 12.0.1 version here with the same process: https://github.com/vahempio/Tasmota-for-eWeLink/blob/tasmota-vahempio/bin/tasmota32-PCA9685_12.0.1.factory.bin

Keep me informed!

**Comment by dongourdet** [comment]
@vahempio Thanks for your fast response.
I'll try that later on tonight. (Fingers crossed)
I'll keep you informed!

**Comment by dongourdet** [comment]
@vahempio I finally got it to work. I used your firmware but I got an invalid signature when i tried to do firmware update of bin/ncp-uart-sw-6.7.9_115200.ota
I erased and then flashed with my own firmware and it worked.
Ethernet is also working 100% Happy!
Thanks for you help!!

**Comment by vahempio** [comment]
Happy to read this, thanks for the feeback and enjoy your fresh device! :)
