### ISSUE TITLE
Does the firmware support zigbee2mqtt?

### ISSUE THREAD

**Issue by hyperlau** [vahempio/Tasmota-for-eWeLink#7]
HI,you have a good job with the device,Thank You for that!
when I config zigbee2mqtt with:(192.168.1.136 is the zigbee bridge device with tasmota32-v12.0.2-EWELINK.bin,I read your answer in the other issue ),
```
serial:
  port: tcp://192.168.1.136:8888

```
zigbee2mqtt log is：
```
Zigbee2MQTT:error 2022-09-17 15:56:37: Exiting...
Zigbee2MQTT:error 2022-09-17 15:56:38: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:109:5)
```
some thing in the tasmota console log tell me the z2m try to connect to the zigbee bridge but did't got the right response:
```
16:58:46.350 TCP: Got connection from 192.168.1.27
16:58:46.353 TCP: to MCU/1: EF
16:58:47.397 TCP: to MCU/1: FE00210120
16:58:53.402 TCP: to MCU/1: FE00210120
16:58:59.405 TCP: to MCU/1: FE00210120
```

can you help me?

**Comment by vahempio** [comment]
Hi!
Unfortunately this firmware has not been designed to be compatible with zigbee2mqtt out of the box. I recommend you to find a close device in the following list https://www.zigbee2mqtt.io/guide/adapters/#recommended (the CC chip should be the same) and perhaps find the right Tasmota config to match the mqtt part.

Happy hack! 🤞

**Comment by vahempio** [comment]
4 months without activity on this issue, I close it. Don't hesitate to post a new comment if you have news!
